basicapp/urls.py
from django.urls import path
from basicapp import views

app_name = 'basicapp'

urlpatterns = [
    path('register/', views.registration, name='registration'),
    path('user_login', views.login, name='user_login'),
]

learning_users/urls.py
from django.contrib import admin
from django.urls import path,include
from basicapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name='index'),
    path('basicapp/',include('basicapp.urls')),
    path('logout/', views.logout,name='logout'),
    path('special/', views.special,name='special'),
]

basicapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileinfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    # additional
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

basicapp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicapp.models import UserProfileinfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileinfoForm(forms.ModelForm):      
    class Meta():
        model = UserProfileinfo
        fields = ('portfolio_site','profile_pic')

basicapp/views.py
from django.shortcuts import render
from basicapp.forms import UserForm, UserProfileinfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    return render(request,'basicapp/index.html')


@login_required
def special(request):
    return HttpResponse("You're succesfully logged in,Nice!")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def registration(request):
    registered =False
    if request.method == "POST":
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileinfoForm(data = request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit = False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered=True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form=UserForm()
        profile_form = UserProfileinfoForm()
    return render(request,"basicapp/registration.html", {
        'user_form': user_form,
        'profile_form': profile_form,
        'registered': registered
    })

    def user_login(request):
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(username=username,password=password)
            if user:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse('index'))
                else:
                    return HttpResponse('ACCOUNT ISNOT ACTIVE')
            else:
                print("Someone tried to logged in and failed")
                print("username:{} and password:{}".format(username,password))
                return HttpResponse("Invalid login details")
        else:
            return render(request,'basicapp/login.html',{})

basicapp/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Basic</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
</head>
<body>
    <div class="container">
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'index' %}">Brand</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                  <li class="active"><a href="{% url 'admin:index' %}">ADMIN </a></li>
                  <li><a href="{% url 'basicapp:registration' %}">REGISTER</a></li>

                  {% if user.is_authenticated %}
                    <li><a href="{% url 'logout'%}">Logout</a></li>
                  {% else %}
                    <li><a href="{%url 'basicapp:user_login'%}">LogIn</a></li>
                {% endif %}
                </ul>
            </div>
        </div>
      </nav>
    </div>

    
    <div class="container">
        {% block body_block %}
        <!--anything outside the box will be inherit if we use extends-->
        {% endblock %}
    </div>
</body>
</html>

basicapp/templates/basicapp/index.html
{% extends "basicapp/base.html" %}
  {% block body_block %}
  <div class="container">
    <div class="jumbotron">
    <h1>welcome to index</h1>
    <h2>it is a example</h2>
</div>
</div>


  {% endblock %}

basicapp/templates/basicapp/login.html
{% extends "basicapp/base.html" %}

{% block body_block %}

<div class="jumbotron">
    <h1>please LogIn</h1>
    <form action="{% url 'basicapp:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">USERNAME</label>
        <input type="text" id="username" name="username" placeholder="enter your name">
        <label for="password">PASSWORD</label>
        <input type="password" id="password" name="password">

        <input type="submit" value="LogIn">
    </form>
</div>

{% endblock %}

basicapp/templates/basicapp/registration.html
{% extends "basicapp/base.html" %}
{% load staticfiles %}
{% block body_block %}
<div class="jumbotron">
    {% if registered %}
        <h1>THANK YOU FOR REGISTERING</h1>
    {% else %}
        <h1>REGISTER HERE</h1>
        <h3>FILL UP THE FORM</h3>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" value="register">
        </form>
    {% endif %}
</div>
{% endblock %}